MT50_task_descriptions = {
    "assembly": 'Pick up a nut and place it onto a peg.',
    "basketball": 'Dunk the basketball into the basket.',
    "bin-picking": 'Grasp the puck from one bin and place it into another bin.',
    "box-close": 'Grasp the cover and close the box with it.',
    "button-press-topdown": 'Press a button from the top.',
    "button-press-topdown-wall": 'Bypass a wall and press a button from the top.',
    "button-press": 'Press a button.',
    "button-press-wall": 'Bypass a wall and press a button.',
    "coffee-button": 'Push a button on the coffee machine.',
    "coffee-pull": 'Pull a mug from a coffee machine.',
    "coffee-push": 'Push a mug under a coffee machine.',
    "dial-turn": 'Rotate a dial 180 degrees.',
    "disassemble": 'Pick a nut out of the a peg.',
    "door-close": 'Close a door with a revolving joint.',
    "door-lock": 'Lock the door by rotating the lock clockwise.',
    "door-open": 'Open a door with a revolving joint.',
    "door-unlock": 'Unlock the door by rotating the lock counter-clockwise.',
    "hand-insert": 'Insert the gripper into a hole.',
    "drawer-close": 'Push and close a drawer.',
    "drawer-open": 'Open a drawer.',
    "faucet-open": 'Rotate the faucet counter-clockwise.',
    "faucet-close": 'Rotate the faucet clockwise.',
    "hammer": 'Hammer a screw on the wall.',
    "handle-press-side": 'Press a handle down sideways.',
    "handle-press": 'Press a handle down.',
    "handle-pull-side": 'Pull a handle up sideways.',
    "handle-pull": 'Pull a handle up.',
    "lever-pull": 'Pull a lever down 90 degrees.',
    "peg-insert-side": 'Insert a peg sideways.',
    "peg-unplug-side": 'Unplug a peg sideways.',
    "pick-place-wall": 'Pick a puck, bypass a wall and place the puck.',
    "pick-out-of-hole": 'Pick up a puck from a hole.',
    "pick-place": 'Pick and place a puck to a goal.',
    "plate-slide": 'Slide a plate into a cabinet.',
    "plate-slide-side": 'Slide a plate into a cabinet sideways.',
    "plate-slide-back": 'Get a plate from the cabinet.',
    "plate-slide-back-side": 'Get a plate from the cabinet sideways.',
    "push": 'Push the puck to a goal.',
    "push-wall": 'Bypass a wall and push a puck to a goal.',
    "push-back": 'Pull a puck to a goal.',
    "reach": 'Reach a goal position.',
    "reach-wall": 'Bypass a wall and reach a goal.',
    "shelf-place": 'Pick and place a puck onto a shelf.',
    "soccer": 'Kick a soccer into the goal.',
    "stick-push": 'Grasp a stick and push a box using the stick.',
    "stick-pull": 'Grasp a stick and pull a box with the stick.',
    "sweep-into": 'Sweep a puck into a hole.',
    "sweep": 'Sweep a puck off the table.',
    "window-open": 'Push and open a window.',
    "window-close": 'Push and close a window.'
}